package simple;

/**
 * Generated by jlemon.
 * But file must be renamed from `parser.h`to `TokenType.java`.
 * And package must be specified manually
 */
public interface TokenType {
  int PLUS                           =   1;
  int MINUS                          =   2;
  int DIVIDE                         =   3;
  int TIMES                          =   4;
  int INTEGER                        =   5;
  static String String(int token) {
    switch(token) {
    case 1  : return "PLUS";
    case 2  : return "MINUS";
    case 3  : return "DIVIDE";
    case 4  : return "TIMES";
    case 5  : return "INTEGER";
    }
    throw new AssertionError(String.format("Unexpected token: %d", token));
  }
}
